name: Build Notificacion Service (PostgreSQL + Maven)

on:
  push:
    paths:
      - 'notificacion-service/**'
  pull_request:
    paths:
      - 'notificacion-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: urbike
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Build notificacion-service
        working-directory: notificacion-service
        env:
          USER: postgres
          PASSWORD: postgres
          SECRET: 1234567
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/urbike
          MAIL_EMAIL: urbike77@gmail.com
          MAIL_PASSWORD: voow epdd zpjj qktu
        run: mvn -B clean package
